module AppConstants
  ADMIN             = 'AdminProfile'
  MEMBER            = 'MemberProfile'
  DEVICE_IOS        = 'ios'
  DEVICE_ANDR       = 'android'
  DEVICE_WEB        = 'web'
  MEMBER_FOLLOWINGS = 'member_followings'
  MEMBER_FOLLOWERS  = 'member_followers'
  ACCEPTED          = 'accepted'
  PENDING           = 'pending'
  REJECTED          = 'rejected'
  TIMELINE          =  'TimeLine'
  
  SEARCH   = 'search'
  UPCOMING = 'upcoming'
  DAY      = 'day'
  NP_DAY   = 'np_day'
  WEEK     = 'week'
  ALL      = 'all'
  PAST     = 'past'
  INVITED  = 'invited'
  REGISTERED = 'registered'
  BOOKMARK  = 'bookmarked'
  NEAR_ME   = 'near_me'
  FOLLOWING = 'following'
  HERE_NOW  = 'here_now'
  GONE      = 'GONE'
  ON_WAY    = 'on_way'
end
